### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by cecil211-mch** [skye8-tech/s8-ims#11]
The landing page will contain
 . A section where a user can logIn
 . An applicant can apply for internship

**Comment by mulfranck** [comment]
I change the issue title, please create a different issue for the `login` page into the directory `src/pages`

**Comment by andrew21-mch** [comment]
check the styling, now well links

**Comment by andrew21-mch** [comment]
@mulfranck  is this completed, 
are the nav items on the landing page working

**Comment by mulfranck** [comment]
Some of the nav items are to be removed. 
Since the issue was to create the page, and the page was created its why I closed the issue.

**Comment by andrew21-mch** [comment]
> Some of the nav items are to be removed. Since the issue was to create the page, and the page was created its why I closed the issue.

I see, then another issue should be open to fix that i guess ?

**Comment by cecil211-mch** [comment]
Sorry I forgot to push

**Comment by mulfranck** [comment]
@cecil211-mch you would just create an issue.
