### ISSUE TITLE
create application form

### ISSUE THREAD

**Issue by Ngumbutlar** [skye8-tech/s8-ims#7]
Implement the application form based on the design using HTML, CSS and JavaScript. Both the personal information and required information will be implemented on the same html page i.e create:
- Eight input fields for the user's name, address,e-mail, name of school, contact, department and start date.
- Three dropdown menu for user to select level, field and the duration for the internship one radio button

**Comment by andrew21-mch** [comment]
you can further separate this into 2 pages, just to ease how you work on it
